services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5441:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=quote_editor_development
    volumes:
      - ./postgres:/var/lib/postgresql/data
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6385:6379"
    command:
      - redis-server --save 20 1 --loglevel warning --maxmemory-policy noeviction
    volumes:
      - ./redis_data:/data

networks:
  default:
    external: true
    name: quote_editor
