services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5441:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=quote_editor_development
    volumes:
      - ./postgres:/var/lib/postgresql/data
  redis:
    image: redis:7.2-alpine
    ports:
      - "6385:6379"
    command:
      - redis-server
    volumes:
      - ./redis_data:/data
      - ./redis_config:/usr/local/etc/redis/redis.conf

networks:
  default:
    external: true
    name: quote_editor
